version: '3'
services:
  production: &prod
    build:
      context: .
    environment:
      - BQ_DATASET
      - BQ_LOCATION
      - BQ_CREDENTIALS_TYPE
      - BQ_CREDENTIALS_PROJECT_ID
      - BQ_CREDENTIALS_PRIVATE_KEY_ID
      - BQ_CREDENTIALS_PRIVATE_KEY
      - BQ_CREDENTIALS_CLIENT_EMAIL
      - BQ_CREDENTIALS_CLIENT_ID
      - BQ_CREDENTIALS_AUTH_URI
      - BQ_CREDENTIALS_TOKEN_URI
      - BQ_CREDENTIALS_AUTH_PROVIDER_X509_CERT_URL
      - BQ_CREDENTIALS_CLIENT_X509_CERT_URL
      - KBC_RUNID
      - KBC_DATA_TYPE_SUPPORT=none
  dev: &dev
    <<: *prod
    image: keboola/google-bigquery-transformation
    volumes:
      - ./:/code
      - ./data:/data
  dev-xdebug:
    <<: *dev
    build: docker/xdebug
    volumes:
      - ./:/code
      - ./data:/data
